import type { QuestionDef } from "../../core/types.js";

export const GIT_BANK: QuestionDef[] = [
  {
    id: "destructive_migration",
    type: "noul",
    instructions: "The push contains a schema migration that drops or truncates data, or renames/removes a column in a way that loses data on deploy.",
    criteria: { true: "Migration files with DROP/TRUNCATE/remove_column style operations on tables that plausibly hold data.", false: "No migrations, or only additive ones (add column, create table, add index)." },
    thresholds: { nudge: 0.5, confirm: 0.75, block: 0.95 },
    reason: "A migration here destroys data ({p}%)",
    weight: 1.5,
  },
  {
    id: "disables_tests_or_checks",
    type: "noul",
    instructions: "The push skips, disables, or deletes tests, or weakens CI checks, without an explanation in the commit messages.",
    criteria: { true: "Added .skip/.only/@skip lines, deleted test files, or loosened CI config, and no commit says why.", false: "Tests and checks are untouched, strengthened, or the skip is explained." },
    thresholds: { nudge: 0.5, confirm: 0.8 },
    reason: "This disables tests or checks ({p}%)",
    weight: 1.2,
  },
  {
    id: "commit_message_contradicts_diff",
    type: "noul",
    instructions: "The commit subjects describe something materially different from what the files and hunks show.",
    criteria: { true: "Subjects say one thing (e.g. 'fix typo') while the diff touches infra, migrations, auth, or many unrelated files.", false: "Subjects reasonably describe the diff." },
    thresholds: { nudge: 0.5, confirm: 0.8 },
    reason: "The commit messages don't match the diff ({p}%)",
    weight: 1.0,
  },
  {
    id: "unrelated_changes_bundled",
    type: "noul",
    instructions: "The push mixes unrelated changes that should be separate (feature + infra + formatting + dependency bumps).",
    criteria: { true: "Files span several unrelated areas and the commits don't separate them.", false: "Changes are cohesive or clearly separated by commit." },
    thresholds: { nudge: 0.6, hold: 0.85 },
    reason: "Unrelated changes are bundled ({p}%)",
    weight: 0.5,
  },
  {
    id: "infra_change_unmentioned",
    type: "noul",
    instructions: "Infrastructure, CI, deployment, or configuration files change, and no commit message mentions it.",
    criteria: { true: "CI/infra/config files are in the diff and the subjects are silent about them.", false: "No such files, or the subjects mention the change." },
    thresholds: { nudge: 0.5, confirm: 0.8 },
    reason: "Infra or CI changed without being mentioned ({p}%)",
    weight: 1.0,
  },
  {
    id: "not_ready_to_share",
    type: "noul",
    instructions: "The push looks unfinished: WIP subjects, leftover debug output, TODO/FIXME in new code, or a branch being pushed to a protected name.",
    criteria: { true: "WIP-style subjects, debugger/console.log/print additions, or obvious placeholders.", false: "Commits read as complete." },
    thresholds: { nudge: 0.6, hold: 0.8 },
    reason: "This looks unfinished ({p}%)",
    weight: 0.6,
  },
  {
    id: "off_hours_to_protected",
    type: "noul",
    instructions: "A push to a protected or deployed branch late in the day or week, when a problem would be hard to catch quickly.",
    criteria: { true: "Protected branch, and the local time is a late evening or Friday afternoon or weekend.", false: "Not protected, or normal working hours." },
    thresholds: { nudge: 0.6, hold: 0.8 },
    reason: "Off-hours push to a protected branch ({p}%)",
    weight: 0.5,
  },
  {
    id: "blast_radius",
    type: "score",
    instructions: "If this push is a mistake, how bad is it?",
    criteria: ["nothing: a personal branch", "small: a feature branch others may pull", "medium: a shared branch, easily reverted", "large: a deployed branch or a data change", "severe: irreversible data loss or a security regression"],
    weight: 0,
  },
];
