// Turns packs/*.pack.yaml into src/generated/packs.ts so the browser extension shares the YAML source of truth.
import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadPack } from "../src/pack/loader.js";

const dir = "packs";
const out: Record<string, unknown> = {};
for (const f of readdirSync(dir).filter((f) => f.endsWith(".pack.yaml"))) {
  const p = loadPack(join(dir, f));
  out[p.name] = { name: p.name, version: p.version, surface: p.surface, l0: p.l0, questions: p.questions.map(({ reasonFor: _r, ...q }) => q) };
}
mkdirSync("src/generated", { recursive: true });
writeFileSync("src/generated/packs.ts", `// generated by scripts/packs-to-json.ts — do not edit\nimport type { QuestionDef, VerdictLevel } from "../core/types.js";\nexport interface PackJson { name: string; version: number; surface: string; l0: Record<string, VerdictLevel>; questions: QuestionDef[] }\nexport const PACKS: Record<string, PackJson> = ${JSON.stringify(out, null, 2)} as unknown as Record<string, PackJson>;\n`);
console.log(`wrote src/generated/packs.ts (${Object.keys(out).join(", ")})`);
