import type { QuestionDef } from "../../core/types.js";

export const PAYMENT_BANK: QuestionDef[] = [
  {
    id: "justification_covers_anomaly",
    type: "noul",
    instructions: "Given the stated facts (first-time payee, amount vs history, changed bank details, timing), does the memo, invoice text, or request explain why this payment is legitimate despite them? Answer whether the anomaly is UNEXPLAINED.",
    criteria: { true: "The facts show something unusual and nothing in the text accounts for it.", false: "Nothing unusual, or the text plausibly explains the unusual part (new contract, annual invoice, agreed change)." },
    thresholds: { nudge: 0.45, confirm: 0.7 },
    reason: "The anomaly isn't explained anywhere ({p}%)",
    weight: 1.2,
  },
  {
    id: "bec_pattern",
    type: "noul",
    instructions: "This looks like business email compromise or vendor-impersonation fraud: urgency, secrecy, a request from an executive name via message, new or recently changed bank details, pressure not to verify by phone.",
    criteria: { true: "Two or more of: urgency words, secrecy, executive-name pressure, message-channel request, changed or new bank details, lookalike payee.", false: "Routine request with none or one weak signal." },
    thresholds: { nudge: 0.35, confirm: 0.55, block: 0.85 },
    reason: "This matches a fraud pattern ({p}%)",
    weight: 1.8,
  },
  {
    id: "invoice_inconsistent",
    type: "noul",
    instructions: "The invoice text disagrees with the payment: different payee name, different amount, different currency, services that don't match the vendor, or dates that don't make sense.",
    criteria: { true: "A material inconsistency between invoice text and the payment fields.", false: "Invoice and payment agree, or no invoice text is provided." },
    thresholds: { nudge: 0.5, confirm: 0.75 },
    reason: "The invoice doesn't match the payment ({p}%)",
    weight: 1.1,
  },
  {
    id: "no_plausible_business_purpose",
    type: "noul",
    instructions: "Nothing in the memo, invoice, or request says what this payment is for in a way that fits the payee and amount.",
    criteria: { true: "Purpose is absent, vague, or does not fit the vendor.", false: "A concrete, fitting purpose is stated." },
    thresholds: { nudge: 0.5, hold: 0.7 },
    reason: "No clear business purpose ({p}%)",
    weight: 0.7,
  },
  {
    id: "structuring_shape",
    type: "noul",
    instructions: "The amount looks chosen to stay under an approval threshold or to split a larger payment.",
    criteria: { true: "Just under a threshold, a round fraction of a larger figure, or one of several similar recent payments to the same payee.", false: "Amount looks like a normal invoice total." },
    thresholds: { nudge: 0.5, confirm: 0.75 },
    reason: "The amount looks threshold-shaped ({p}%)",
    weight: 0.9,
  },
  {
    id: "fraud_likelihood",
    type: "score",
    instructions: "Overall, how likely is this payment to be fraudulent or a serious mistake?",
    criteria: ["routine", "slightly unusual", "worth a second look", "likely a problem", "almost certainly fraud or error"],
    weight: 0,
  },
];
