import type { QuestionDef } from "../../core/types.js";

export const SHELL_BANK: QuestionDef[] = [
  {
    id: "destructive_on_shared_resource",
    type: "noul",
    instructions: "The command destroys or overwrites something other people or systems depend on: a shared branch, a production namespace, a database, a shared volume, a deployed service.",
    criteria: { true: "The target is plausibly shared or production, and the operation deletes, resets, or overwrites it.", false: "The target is local, personal, scratch, or the operation is read-only or additive." },
    thresholds: { nudge: 0.4, hold: 0.6, confirm: 0.75, block: 0.95 },
    reason: "This destroys something shared ({p}%)",
    weight: 1.4,
  },
  {
    id: "wrong_context_for_intent",
    type: "noul",
    instructions: "The active context (kube context, AWS profile, git branch, cwd) does not match what the command seems intended for — e.g. a dev-sounding command while pointed at prod, or vice versa.",
    criteria: { true: "Command wording and the active context disagree about the environment.", false: "Context and command agree, or the context is unknown." },
    thresholds: { nudge: 0.5, confirm: 0.75 },
    reason: "Your context may be wrong for this ({p}%)",
    weight: 1.2,
  },
  {
    id: "skipped_available_dry_run",
    type: "noul",
    instructions: "The tool offers a dry-run or plan mode, the operation is consequential, and the command does not use it.",
    criteria: { true: "A dry-run/plan/--check exists for this tool, the command changes state, and it is not used.", false: "Dry-run is used, unavailable, or the command is trivial." },
    thresholds: { nudge: 0.6, hold: 0.8 },
    reason: "There's a dry run you skipped ({p}%)",
    weight: 0.6,
  },
  {
    id: "affects_many_resources",
    type: "noul",
    instructions: "Wildcards, recursion, or selectors make the command hit many files, records, or resources at once.",
    criteria: { true: "Globs, -r/-R, --all, label selectors, or unqualified targets broaden the effect.", false: "The command names a single, specific target." },
    thresholds: { nudge: 0.5, hold: 0.75 },
    reason: "This touches a lot at once ({p}%)",
    weight: 0.7,
  },
  {
    id: "irreversible",
    type: "noul",
    instructions: "The effect cannot be undone from the shell afterwards.",
    criteria: { true: "Permanent deletion, published artifact, pushed history rewrite, dropped data, remote destruction.", false: "Reversible, idempotent, or recoverable from version control or backups." },
    thresholds: { nudge: 0.6, confirm: 0.85 },
    reason: "This can't be undone ({p}%)",
    weight: 1.0,
  },
  {
    id: "looks_like_a_slip",
    type: "noul",
    instructions: "The command looks like a typo, a wrong path, a wrong flag, or a half-edited line rather than what the person meant.",
    criteria: { true: "Odd spacing, a path that doesn't fit the cwd, a flag in the wrong place, an unbalanced quote, or a target that looks mistyped.", false: "The command reads as deliberate and well-formed." },
    thresholds: { nudge: 0.5, confirm: 0.8 },
    reason: "This might be a slip ({p}%)",
    weight: 0.9,
  },
  {
    id: "blast_radius",
    type: "score",
    instructions: "If this command is a mistake, how bad is it?",
    criteria: ["nothing: trivially undone", "annoying: a few minutes to recover", "painful: hours, or someone else affected", "serious: production or data loss", "catastrophic: unrecoverable or company-wide"],
    weight: 0,
  },
];
