// esbuild: the side panel (the whole runtime), the background worker, the region-picker content script; copies
// static files; bundles every pack.yaml under ../packs as text so the extension ships with the packs.
import { build } from "esbuild";
import { cpSync, mkdirSync, readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

mkdirSync("dist", { recursive: true });
const packsDir = join("..", "packs");
const packs = {};
for (const name of readdirSync(packsDir)) {
  const p = join(packsDir, name, "pack.yaml");
  if (existsSync(p)) packs[name] = readFileSync(p, "utf8");
}
// the pool index: every pack with a `pool:` section (urls it applies to) becomes an entry other installs can find
import yaml from "js-yaml";
const pool = { generated: new Date().toISOString().slice(0, 10), packs: [] };
for (const [name, text] of Object.entries(packs)) {
  let raw = {}; try { raw = yaml.load(text) ?? {}; } catch { continue; }
  const hint = raw.pool ?? {};
  pool.packs.push({ name, game: raw.game, urls: hint.urls ?? [], yaml_url: `https://raw.githubusercontent.com/Dhruv123-123/jevvingaround/main/anygame/packs/${name}/pack.yaml`, fingerprints: raw.fingerprints ?? {} });
}
writeFileSync(join(packsDir, "pool.json"), JSON.stringify(pool, null, 1) + "\n");
writeFileSync("src/packs.generated.ts", "// generated by build.mjs\nexport const BUNDLED_PACKS: Record<string, string> = " + JSON.stringify(packs, null, 0) + ";\n");
const common = { bundle: true, format: "esm", target: "chrome120", sourcemap: true, logLevel: "warning" };
await build({ ...common, entryPoints: ["src/panel/panel.ts"], outfile: "dist/panel.js" });
await build({ ...common, entryPoints: ["src/background.ts"], outfile: "dist/background.js" });
await build({ ...common, entryPoints: ["src/region.ts"], outfile: "dist/region.js", format: "iife" });
await build({ ...common, entryPoints: ["src/record.ts"], outfile: "dist/record.js", format: "iife" });
await build({ ...common, entryPoints: ["src/core/index.ts"], outfile: "dist/core.js", platform: "neutral" });
for (const f of ["manifest.json", "src/panel/panel.html", "src/panel/panel.css"]) cpSync(f, join("dist", f.split("/").pop()));
cpSync("icons", "dist/icons", { recursive: true });
console.log(`built dist/ with ${Object.keys(packs).length} packs: ${Object.keys(packs).join(", ")}`);
